# Brewfile for personal workspace

brew "handbrake"
# Need to build from source to address mismatch of versions between
# Perl and MusicBrainz:DiscId
brew "abcde", args: [ "build-from-source" ]
brew "cd-discid"
brew "flac"
brew "lame"
brew "eye-d3"
brew "ffmpeg"
brew "lsdvd"

cask "google-drive"
cask "signal"
